name: Update M3U List
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Tüm commit geçmişini çek

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch M3U
        run: python fetch_m3u.py

      - name: Commit Changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add tv_listesi.m3u
          git diff --cached --quiet || git commit -m "📺 M3U Güncelleme [$(date +'%d.%m.%Y %H:%M')]"
          git push
