name: Update Kablo TV
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 6 SAATTE BİR (UTC)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Generate M3U
        run: python kablo_api.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kablo_tv.m3u
          git commit -m "Auto-update [$(date +'%d.%m.%Y %H:%M')]"
          git push
